TraineeTracker/TraineeTracker.App/Models/Tracker.cs
using Microsoft.AspNetCore.Mvc.ModelBinding.Validation;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace TraineeTracker.App.Models
{
    public class Tracker
    {

        [Key]
        public int Id { get; set; }

        [StringLength(50)]
        [Required(ErrorMessage = "Title is required")]
        public string Title { get; set; } = null!;

        [StringLength(500)]
        [DisplayName("Start")]
        public string? StartDoingText { get; set; }

        [StringLength(500)]
        [DisplayName("Stop")]
        public string? StopDoingText { get; set; }

        [StringLength(500)]
        [DisplayName("Continue")]
        public string? ContinueDoingText { get; set; }

        [DisplayName("Reviewed")]
        public bool IsReviewed { get; set; }

        public string TechnicalSkill { get; set; } = "Partially Skilled";

        public string SpartanSkill { get; set; } = "Partially Skilled";

        [DisplayName("Date")]
        [DataType(DataType.Date)]
        public DateTime DateCreated { get; set; } = DateTime.Now;

        public Spartan? Spartan { get; set; }

        [ValidateNever]
        [ForeignKey("Spartan")]
        public string SpartanId { get; set; } = null!;


    }
}

TraineeTracker/TraineeTracker.App/Controllers/TrackersController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System.Data;
using TraineeTracker.App.Models.ViewModels;
using TraineeTracker.App.Services;

namespace TraineeTracker.App.Controllers
{
    [Authorize]
    public class TrackersController : Controller
    {
        private readonly ITrackerService _service;

        public TrackersController(ITrackerService service)
        {
            _service = service;
        }

        // GET: Trackers
        [Authorize(Roles = "Trainee, Trainer, Admin")]
        public async Task<IActionResult> Index(string? filter = null)
        {
            var user = await _service.GetUserAsync(HttpContext);
            var response = await _service.GetTrackersAsync(user.Data, _service.GetRole(HttpContext), filter);
            return response.Success ? View(response.Data) : Problem(response.Message);
        }

        // GET: Trackers/Details/5
        [Authorize(Roles = "Trainee, Trainer, Admin")]
        public async Task<IActionResult> Details(int? id)
        {
            var user = await _service.GetUserAsync(HttpContext);
            var response = await _service.GetDetailsAsync(user.Data, id, _service.GetRole(HttpContext));
            return response.Success ? View(response.Data) : Problem(response.Message);
        }

        // GET: Trackers/Create
        [Authorize(Roles = "Trainee, Admin")]
        public IActionResult Create()
        {
            return View();
        }

        // POST: Trackers/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Trainee, Admin")]
        public async Task<IActionResult> Create(CreateTrackerVM createTrackerVM)
        {
            var user = await _service.GetUserAsync(HttpContext);
            var response = await _service.CreateTrackerAsync(user.Data, createTrackerVM);
            return response.Success ? RedirectToAction(nameof(Index)) : View(createTrackerVM);
        }

        // GET: Trackers/Edit/5
        [Authorize(Roles = "Trainee, Trainer, Admin")]
        public async Task<IActionResult> Edit(int? id)
        {
            var user = await _service.GetUserAsync(HttpContext);
            var response = await _service.GetDetailsAsync(user.Data, id, _service.GetRole(HttpContext));
            return response.Success ? View(response.Data) : Problem(response.Message);
        }

        // POST: Trackers/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Trainee, Admin")]
        public async Task<IActionResult> Edit(int id, TrackerVM trackerVM)
        {
            var user = await _service.GetUserAsync(HttpContext);
            var response = await _service.EditTrackerAsync(user.Data, id, trackerVM);
            return response.Success ? RedirectToAction(nameof(Index)) : NotFound();
        }

        // POST: Trackers/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Trainee, Trainer, Admin")]
        public async Task<IActionResult> Delete(int id)
        {
            var user = await _service.GetUserAsync(HttpContext);
            var response = await _service.DeleteTrackerAsync(user.Data, id);
            return response.Success ? RedirectToAction(nameof(Index)) : Problem(response.Message);
        }

        [Authorize(Roles = "Trainee, Admin")]
        public async Task<IActionResult> UpdateTrackerReviewed(int id, MarkReviewedVM markReviewedVM)
        {
            var user = await _service.GetUserAsync(HttpContext);
            var response = await _service.UpdateTrackerReviewedAsync(user.Data, id, markReviewedVM);
            return response.Success ? RedirectToAction(nameof(Index)) : Problem(response.Message);
        }
    }
}

TraineeTracker/TraineeTracker.App/Views/Trackers/Create.cshtml
@model TraineeTracker.App.Models.ViewModels.CreateTrackerVM

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Tracker</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Title" class="control-label"></label>
                <input asp-for="Title" class="form-control" />
                <span asp-validation-for="Title" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="StartDoingText" class="control-label"></label>
                <textarea asp-for="StartDoingText" class="form-control rounded-0" rows="10"></textarea>
                <span asp-validation-for="StartDoingText" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="StopDoingText" class="control-label"></label>
                <textarea asp-for="StopDoingText" class="form-control rounded-0" rows="10"></textarea>
                <span asp-validation-for="StopDoingText" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ContinueDoingText" class="control-label"></label>
                <textarea asp-for="ContinueDoingText" class="form-control rounded-0" rows="10"></textarea>
                <span asp-validation-for="ContinueDoingText" class="text-danger"></span>
            </div>
            <div class="form-group form-check">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="IsReviewed" /> @Html.DisplayNameFor(model => model.IsReviewed)
                </label>
            </div>
            @*Create a down menu to choose from, with "Partially Selected" as default*@
            <div class="form-group">
                <label asp-for="TechnicalSkill" class="control-label"></label>
                @{
                    List<SelectListItem> techSkills = new List<SelectListItem>();
                    techSkills.Add(new SelectListItem
                    {
                        Text = "Skilled",
                        Value = "Skilled"
                    });
                    techSkills.Add(new SelectListItem
                    {
                        Text = "Partially Skilled",
                        Value = "Partially Skilled",
                        //Selected = true
                    });
                    techSkills.Add(new SelectListItem
                    {
                        Text = "Low Skilled",
                        Value = "Low Skilled"
                    });
                    techSkills.Add(new SelectListItem
                    {
                        Text = "Unskilled",
                        Value = "Unskilled"
                    });
                }
                @Html.DropDownList("TechnicalSkill", techSkills, new { @class = "form-control" })
                <span asp-validation-for="TechnicalSkill" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="SpartanSkill" class="control-label"></label>
                @{
                    List<SelectListItem> spartanSkills = new List<SelectListItem>();
                    spartanSkills.Add(new SelectListItem
                    {
                        Text = "Skilled",
                        Value = "Skilled"
                    });
                    spartanSkills.Add(new SelectListItem
                    {
                        Text = "Partially Skilled",
                        Value = "Partially Skilled",
                        //Selected = true
                    });
                    spartanSkills.Add(new SelectListItem
                    {
                        Text = "Low Skilled",
                        Value = "Low Skilled"
                    });
                    spartanSkills.Add(new SelectListItem
                    {
                        Text = "Unskilled",
                        Value = "Unskilled"
                    });
                }
                @Html.DropDownList("SpartanSkill", spartanSkills, new { @class = "form-control" })
                <span asp-validation-for="SpartanSkill" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

TraineeTracker/TraineeTracker.App/Views/Trackers/Delete.cshtml
@model TraineeTracker.App.Models.ViewModels.TrackerVM

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Tracker</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Title)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Title)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.StartDoingText)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.StartDoingText)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.StopDoingText)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.StopDoingText)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ContinueDoingText)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ContinueDoingText)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.IsReviewed)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.IsReviewed)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.TechnicalSkill)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.TechnicalSkill)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.SpartanSkill)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.SpartanSkill)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.DateCreated)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.DateCreated)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

TraineeTracker/TraineeTracker.App/Views/Trackers/Details.cshtml
@model TraineeTracker.App.Models.ViewModels.TrackerVM

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Tracker</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Title)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Title)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.StartDoingText)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.StartDoingText)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.StopDoingText)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.StopDoingText)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ContinueDoingText)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ContinueDoingText)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.IsReviewed)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.IsReviewed)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.TechnicalSkill)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.TechnicalSkill)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.SpartanSkill)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.SpartanSkill)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.DateCreated)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.DateCreated)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

TraineeTracker/TraineeTracker.App/Views/Trackers/Edit.cshtml
@model TraineeTracker.App.Models.ViewModels.TrackerVM

@{
	ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Tracker</h4>
<hr />
<div class="row">
	<div class="col-md-4">
		<form asp-action="Edit">
			<div asp-validation-summary="ModelOnly" class="text-danger"></div>
			<input type="hidden" asp-for="Id" />
			<div class="form-group">
				<label asp-for="Title" class="control-label"></label>
				<input asp-for="Title" class="form-control" />
				<span asp-validation-for="Title" class="text-danger"></span>
			</div>
			<div class="form-group">
				<label asp-for="StartDoingText" class="control-label"></label>
				<textarea maxlength="499" asp-for="StartDoingText" class="form-control rounded-0" rows="10"></textarea>
				<span asp-validation-for="StartDoingText" class="text-danger"></span>
			</div>
			<div class="form-group">
				<label asp-for="StopDoingText" class="control-label"></label>
				<textarea maxlength="499" asp-for="StopDoingText" class="form-control rounded-0" rows="10"></textarea>
				<span asp-validation-for="StopDoingText" class="text-danger"></span>
			</div>
			<div class="form-group">
				<label asp-for="ContinueDoingText" class="control-label"></label>
				<textarea maxlength="499" asp-for="ContinueDoingText" class="form-control rounded-0" rows="10"></textarea>
				<span asp-validation-for="ContinueDoingText" class="text-danger"></span>
			</div>
			<div class="form-group form-check">
				<label class="form-check-label">
					<input class="form-check-input" asp-for="IsReviewed" /> @Html.DisplayNameFor(model => model.IsReviewed)
				</label>
			</div>
			<div class="form-group">
				<label asp-for="TechnicalSkill" class="control-label"></label>
				@{
					List<SelectListItem> techSkills = new List<SelectListItem>();
					techSkills.Add(new SelectListItem
					{
						Text = "Skilled",
						Value = "Skilled"
					});
						techSkills.Add(new SelectListItem
					{
						Text = "Partially Skilled",
						Value = "Partially Skilled",
						//Selected = true
					});
						techSkills.Add(new SelectListItem
					{
						Text = "Low Skilled",
						Value = "Low Skilled"
					});
						techSkills.Add(new SelectListItem
					{
						Text = "Unskilled",
						Value = "Unskilled"
					});
				}
				@Html.DropDownList("TechnicalSkill", techSkills, new { @class = "form-control" })
				<span asp-validation-for="TechnicalSkill" class="text-danger"></span>
			</div>
			<div class="form-group">
				<label asp-for="SpartanSkill" class="control-label"></label>
				@{
					List<SelectListItem> spartanSkills = new List<SelectListItem>();
					spartanSkills.Add(new SelectListItem
					{
						Text = "Skilled",
						Value = "Skilled"
					});
						spartanSkills.Add(new SelectListItem
					{
						Text = "Partially Skilled",
						Value = "Partially Skilled",
						//Selected = true
					});
						spartanSkills.Add(new SelectListItem
					{
						Text = "Low Skilled",
						Value = "Low Skilled"
					});
						spartanSkills.Add(new SelectListItem
					{
						Text = "Unskilled",
						Value = "Unskilled"
					});
				}
				@Html.DropDownList("SpartanSkill", spartanSkills, new { @class = "form-control" })
				<span asp-validation-for="SpartanSkill" class="text-danger"></span>
			</div>
			<div class="form-group">
				<label asp-for="DateCreated" class="control-label"></label>
				<input asp-for="DateCreated" class="form-control" readonly/>
				<span asp-validation-for="DateCreated" class="text-danger"></span>
			</div>
			<div class="form-group">
				<input type="submit" value="Save" class="btn btn-primary" />
			</div>
		</form>
	</div>
</div>

<div>
	<a asp-action="Index">Back to List</a>
</div>

@section Scripts {
	@{
		await Html.RenderPartialAsync("_ValidationScriptsPartial");
	}
}

TraineeTracker/TraineeTracker.App/Views/Trackers/Index.cshtml
@model IEnumerable<TraineeTracker.App.Models.ViewModels.TrackerVM>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>

<form asp-controller="Trackers" asp-action="Index" method="get">
    <p>
        <label for="filter">Filter by: </label>
        <input type="text" id="filter" name="filter" />
        <button type="submit">Filter</button>
    </p>
</form>

<table class="table">
    <thead>
        <tr>
            @{
                if (this.User.IsInRole("Trainer") || this.User.IsInRole("Admin"))
                {
                        <th>
                        @Html.DisplayNameFor(model => model.Spartan.UserName)
                        </th>
                }
            }
            <th>
                @Html.DisplayNameFor(model => model.Title)
            </th>
            <th>
                
            </th>
            <th>
                @Html.DisplayNameFor(model => model.IsReviewed)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.TechnicalSkill)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.SpartanSkill)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.DateCreated)
            </th>
            
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {

            var startText = Utilities.DisplayText(item.StartDoingText, 50);
            var stopText = Utilities.DisplayText(item.StopDoingText, 50);
            var contText = Utilities.DisplayText(item.ContinueDoingText, 50);
        <tr>
            @{
                if (this.User.IsInRole("Trainer") || this.User.IsInRole("Admin"))
                {
                    <td>
                            @Html.DisplayFor(modelitem => item.Spartan.UserName)
                    </td>
                }
            }
            <td>
                @Html.DisplayFor(modelItem => item.Title)
            </td>
            <td>
                <div id="TextFields">
                    <table>
							<tbody>
								<tr><td><strong>@Html.DisplayNameFor(modelItem=>item.StartDoingText):</strong> @Html.DisplayFor(modelItem => startText)</td></tr>
                                <tr><td><strong>@Html.DisplayNameFor(modelItem=>item.StopDoingText):</strong> @Html.DisplayFor(modelItem => stopText)</td></tr>
                                <tr><td><strong>@Html.DisplayNameFor(modelItem=>item.ContinueDoingText):</strong> @Html.DisplayFor(modelItem => contText)</td></tr>
							</tbody>
                    </table>
                </div>
            </td>
            <td>
                <form asp-action="UpdateTrackerReviewed" asp-route-id="@item.Id">
                   @Html.CheckBox("IsReviewed", item.IsReviewed, new {onChange="this.form.submit()"})
                </form>
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.TechnicalSkill)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.SpartanSkill)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.DateCreated)
            </td>
            <td class="btn-group-vertical">
                    <a asp-action="Edit" asp-route-id="@item.Id" class="btn btn-primary">Edit</a>
                    <a asp-action="Details" asp-route-id="@item.Id" class="btn btn-info">Details</a> 
                    <a class="btn btn-danger">
                        @using (Html.BeginForm("Delete", "Trackers", new { id = item.Id }))
                        {
                            <input type="submit" class="bg-transparent border-0" value="Delete" onclick="return confirm('Are you sure you wish to delete the entry: @item.Title?')" />
                        }
                    </a>
            </td>
        </tr>
}
    </tbody>
</table>